/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "aukvjoiftfdtnqzbwork"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImF1a3Zqb2lmdGZkdG5xemJ3b3JrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ4MDg4MjEsImV4cCI6MjA3MDM4NDgyMX0.-3x0nqnkYYNX4uf3TPkeOMgv-v8jGDwBx5SafI1930k"